### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by gracefulife** [namics/java-random#9]
I think this library is very helpful.
So, I appreciate your work.
But, I can't understand why do you not provide generate-UUID function?

Generate-UUID function already exists on JDK, but if you provide it in this library, it will help were code consistency.
What do you think?

**Comment by andreschaefer** [comment]
Hello @gracefulife 
There is no explicit method on RandomData so far. Anyway a String representation of UUID ist used to generate Object fields of String named id, guid or uuid.

Any way I will consider to add supporting methods here.

**Comment by gracefulife** [comment]
Thanks !

**Comment by andreschaefer** [comment]
1.1.6 underway incl. changes above
